<?php

/*
 * CommunicatorCorp\Communicator
 *
 * Copyright © 2016 Rippleffect Studio Ltd
 * Rights reserved.
 *
 * PHP version 5.4+
 */

?>
<script type="text/javascript">
    /**
     * Resets the synchronisation counters.
     */
    function resetSynchronisation()
    {
        new Ajax.Request('<?php echo $this->getAjaxResetSynchronisationUrl(); ?>', {
            method: 'get',
            onSuccess: function (response) {
                window.location.reload(true);
            },
            onFailure: function (response) {
                alert('Could not reset the synchronisation counters.');
            }
        });
    }
</script>
<?php
/** CommunicatorCorp_Communicator_Block_Adminhtml_System_Config_Form_ResetButton $this */
echo $this->getButtonHtml();
